# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
    ports:
      - 1433:1433
    volumes:
      - sqlserver:/var/opt/mssql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
        
volumes:
  sqlserver: